# Generated by Django 4.2.14 on 2026-05-28 05:59

import apps.personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_repair_alumni_profile_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.personnel.models.member_avatar_upload_to,
            ),
        ),
    ]
